# Read file

In [39]:
import pandas as pd
data=pd.read_csv("insurance.csv")
display(data.head())

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

# Shape of data

In [40]:
print("we have rows:{}".format(data.shape[0]),
      "\n we have colunms:{}".format(data.shape[1]))

we have rows:1338
 we have colunms:7

# Null values

In [41]:
import numpy as np
display(data.isnull().sum())
np.sum(pd.isnull(data))

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

# unique values in specific coulnms

In [42]:
display(data["smoker"].unique())
display(data["age"].unique())
display(data["sex"].unique())

array(['yes', 'no'], dtype=object)

array([19, 18, 28, 33, 32, 31, 46, 37, 60, 25, 62, 23, 56, 27, 52, 30, 34,
       59, 63, 55, 22, 26, 35, 24, 41, 38, 36, 21, 48, 40, 58, 53, 43, 64,
       20, 61, 44, 57, 29, 45, 54, 49, 47, 51, 42, 50, 39])

array(['female', 'male'], dtype=object)

# fill nulll values

In [43]:
num=data['smoker'].mode()[0]
data['smoker']=data["smoker"].fillna(num)
display(data["smoker"])

0       yes
1        no
2        no
3        no
4        no
       ...
1333     no
1334     no
1335     no
1336     no
1337    yes
Name: smoker, Length: 1338, dtype: object

# covert to int

In [56]:
display(data.info())
data['bmi'] = data.bmi.astype(np.int64)
display(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 62.8+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   int64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   charges   1338 non-null   float64
dtypes: float64(1), int64(3), object(2)
memory usage: 62.8+ KB

None

drop **colunms**

In [52]:
data.drop("region" ,axis=1,inplace=True)
display(data.head())

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

data types of colunms

In [57]:
display(data.dtypes)

age           int64
sex          object
bmi           int64
children      int64
smoker       object
charges     float64
dtype: object

# spliting to x and y

In [60]:
x=data.iloc[:,0:-1]
x.shape
y=data.iloc[:,-1]
y.shape
display(data.shape)

(1338, 6)

# convert obj to int columns

In [64]:
c_columns=x.select_dtypes(['object']).columns
x[c_columns]=x[c_columns].apply(lambda x:pd.factorize(x)[0])